### ISSUE TITLE
Sticky Notes Still Very Laggy 

### ISSUE THREAD

**Issue by sekkit** [lvs1974/NvidiaGraphicsFixup#10]
Hi, amazing fix for 10.13.4 boosted my 1080Ti machine into a super fast rig.
After my personal test, the performance out beat RX580 in metal compatibility and overrall UI smoothness.
BUT sticky notes is still very laggy comparing to RX580 which causing difficulties to drag a finder window.

**Comment by vit9696** [comment]
Hi, glad to hear you got a performance boost, yet I am afraid it is not possible to do any better without NVIDIA support. I suppose continuously mailing them via http://www.nvidia.com/object/driverqualityassurance.html might make some effect.

**Comment by sekkit** [comment]
Many nvidia users like me are so appreciated of this hack work. 
Any donation account out there? if possible please tell us so that people can support your work.
