### ISSUE TITLE
UP3218K Recogonized as Dual Display

### ISSUE THREAD

**Issue by sekkit** [lvs1974/NvidiaGraphicsFixup#12]
2715K works fine, but 3218K recognized as two seperate 8K display@24Hz.
MST support is not fully working.

**Comment by vit9696** [comment]
If https://github.com/PMHeart/CoreDisplayFixup does not help, then it is just another NVIDIA bug, which you are to report to NVIDIA driver team, not us. Please understand, while we indeed solve(d) some issues on macOS, we are not the GeForce support team. Neither we do, nor we intend to fix every single issue existing in NVIDIA drivers, which, believe me, are not in a good shape.

We may accept issues on the stuff we do, but accepting issues on what we do not touch is not really possible. Closing as not applicable.
