### ISSUE TITLE
Black screen after webdriver 387.10.10.10.30.106 update

### ISSUE THREAD

**Issue by kecinzer** [lvs1974/NvidiaGraphicsFixup#16]
Hello,
because I red, that new web driver is good, I tried it. But after install and reboot I have only black screen with GeForce active. I have 1.2.6 version of kext.
When I switch to "Apple drivers" in nVidia setting, it works normaly.

**Comment by vit9696** [comment]
Well, I have no idea what went wrong there. Could be System Integrity Protection or something like that. In my opinion, it is better not to rush and to wait for a fix in the Apple drivers as well. With all due respect Apple drivers have always been more stable for me, so I am not really into experimenting with web unless I really have to.
