### ISSUE TITLE
No releases found

### ISSUE THREAD

**Issue by mastersam92** [lvs1974/NvidiaGraphicsFixup#17]
There isn't release for download.
On sourceforge - nothing( project exists, but, without any files and link here )
On github - nothing( sources only )
Google's results - many articles.. with link here & download form /release

So, where can i download release version of this, so interesting, module ?

**Comment by mastersam92** [comment]
Some found..

[IntelGraphicsFixup.kext.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1982135/IntelGraphicsFixup.kext.zip)

**Comment by vandroiy2013** [comment]
https://github.com/lvs1974/NvidiaGraphicsFixup/releases
