### ISSUE TITLE
Returns [GPU hang: Robust channel error!] [NVDA(DMA): Channel exception!] error while wake from sleep.

### ISSUE THREAD

**Issue by 70599** [lvs1974/NvidiaGraphicsFixup#18]
https://www.insanelymac.com/forum/forum/671-nvidiagraphicsfixup/ returns 404, so I opened this issue.

Here is my PC:
MB: Maximus IV GENE-Z
CPU: i7-2600K
MEM: 16G
GPU: Asus NVIDIA GeForce GTX 570 HD 1280MB
NvidiaGraphicsFixup Ver: 1.2.6

Reproduce flow:
1. Boot with -v, everything working fine
2. Click  then Sleep
3. Wait the PC going into sleep
4. Press power button to wake up
5. Video signal detected but shows only a moveable cursor in the black screen
6. Error code looping after 10+ seconds

Screen for error code:
![img_0062](https://user-images.githubusercontent.com/5929170/41192352-e47a477a-6c2e-11e8-83ba-6e28bf69bfea.JPG)

**Comment by vit9696** [comment]
Hi, that’s a borked GPU firmware ot driver. Consider updating your GOP firmware (e.g. via [GOPUpdate](https://www.win-raid.com/t892f16-AMD-and-Nvidia-GOP-update-No-requests-DIY.html#msg15730) and BIOS first. If this does not work you could try using CSM module or buying AMD.
