### ISSUE TITLE
Native Discrete GPU Power Management.

### ISSUE THREAD

**Issue by ReddestDream** [lvs1974/NvidiaGraphicsFixup#2]
Not sure if you are aware of toleda's efforts here on Native dGPU Power Management:

https://www.tonymacx86.com/threads/macos-native-discrete-gpu-power-management.247479/

https://github.com/toleda/audio_hdmi_amd-nvidia/blob/master/dAGPM.kext.zip

Perhaps this should be integrated into NvidiaGraphicsFixup/WhateverGreen/Shiki themselves at some point?

Thanks!

**Comment by piiiggg** [comment]
Add board-id patch would be great!!!!!!

**Comment by vit9696** [comment]
We were unawhere of toleda's manual, yet AGDP patching is common sense for older GPUs like 8xxx. So far our experiments showed that at least on Kepler GPUs and newer it makes no visible effect, so we hardly see a reason in enabling AGDP on other models. If you could convince us that it does make sense to change, please elaborate your reasons.

**Comment by ReddestDream** [comment]
Okay. I was unaware that you had already tested it and found no improvement on Kepler and newer. I was hoping to see some improvement on Pascal. I'll continue my own tests. Thanks.
