### ISSUE TITLE
I do not find the download link

### ISSUE THREAD

**Issue by jhonathas** [lvs1974/NvidiaGraphicsFixup#5]
Do not think the link to download NvidiaGraphicsFixup.kext. Could you pass me?

**Comment by vandroiy2013** [comment]
[https://github.com/lvs1974/NvidiaGraphicsFixup/releases](url)

**Comment by Lawris** [comment]
Link does not work...

**Comment by Lawris** [comment]
Thanks for the answer ! I actually found a drive where you can download plenty of kexts (regularly updated) : https://onedrive.live.com/?authkey=%21AAODJfuvXMALIpE&id=FE4038DA929BFB23%21427991&cid=FE4038DA929BFB23

I had also had to install Lilu.kext on my Clover kexts to make it work like a charm :)
