### ISSUE TITLE
can't compile 1.2.4

### ISSUE THREAD

**Issue by xelanaiznac** [lvs1974/NvidiaGraphicsFixup#6]
hi lvs1974. thank you for your hard work, really appreciated.
i am newbie in compiling, and I can't compile your 1.2.4 version due to some errors. I'm attaching here a picture about them

[errors.zip](https://github.com/lvs1974/NvidiaGraphicsFixup/files/1864225/errors.zip)

**Comment by canyondust** [comment]
Are you placing the debug version of Lilu.kext in the main NvidiaGraphixFixup folder when you compile? (You need to do that)

**Comment by xelanaiznac** [comment]
Yes. I did it

Inviato da iPhone

**Comment by vandroiy2013** [comment]
Compile latest debug Lilu.kext from master and place it in main NvidiaGraphixFixup folder.
