### ISSUE TITLE
Question: Lag fix for 10.12, too?

### ISSUE THREAD

**Issue by JurekRaben** [lvs1974/NvidiaGraphicsFixup#8]
Hi,

this is fantastic: https://github.com/lvs1974/NvidiaGraphicsFixup/commit/2548a94bce9fe38e855ca17f19bea05978938cd7

Thanks for that. But isn't there a tiny lag problem on Sierra 10.12.6, too? At least for me. It not that obvious like in High Sierra though. Would this patch also work for Sierra?

**Comment by vit9696** [comment]
Hi,

No, sorry. 10.12 indeed has some stuttering issues (although much smaller than 10.13), but the cause is much less obvious than in 10.13. In fact, I do not think these even are the same issues, and investing too much time in fixing 10.12 issues is probably not worth it.
